/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cfg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cfg.pb-c.h"
void   network_config__init
                     (NetworkConfig         *message)
{
  static const NetworkConfig init_value = NETWORK_CONFIG__INIT;
  *message = init_value;
}
size_t network_config__get_packed_size
                     (const NetworkConfig *message)
{
  assert(message->base.descriptor == &network_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t network_config__pack
                     (const NetworkConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &network_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t network_config__pack_to_buffer
                     (const NetworkConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &network_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetworkConfig *
       network_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetworkConfig *)
     protobuf_c_message_unpack (&network_config__descriptor,
                                allocator, len, data);
}
void   network_config__free_unpacked
                     (NetworkConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &network_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kkdcp_realm_config__init
                     (KkdcpRealmConfig         *message)
{
  static const KkdcpRealmConfig init_value = KKDCP_REALM_CONFIG__INIT;
  *message = init_value;
}
size_t kkdcp_realm_config__get_packed_size
                     (const KkdcpRealmConfig *message)
{
  assert(message->base.descriptor == &kkdcp_realm_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kkdcp_realm_config__pack
                     (const KkdcpRealmConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kkdcp_realm_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kkdcp_realm_config__pack_to_buffer
                     (const KkdcpRealmConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kkdcp_realm_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KkdcpRealmConfig *
       kkdcp_realm_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KkdcpRealmConfig *)
     protobuf_c_message_unpack (&kkdcp_realm_config__descriptor,
                                allocator, len, data);
}
void   kkdcp_realm_config__free_unpacked
                     (KkdcpRealmConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kkdcp_realm_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kkdcp_config__init
                     (KkdcpConfig         *message)
{
  static const KkdcpConfig init_value = KKDCP_CONFIG__INIT;
  *message = init_value;
}
size_t kkdcp_config__get_packed_size
                     (const KkdcpConfig *message)
{
  assert(message->base.descriptor == &kkdcp_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kkdcp_config__pack
                     (const KkdcpConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kkdcp_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kkdcp_config__pack_to_buffer
                     (const KkdcpConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kkdcp_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KkdcpConfig *
       kkdcp_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KkdcpConfig *)
     protobuf_c_message_unpack (&kkdcp_config__descriptor,
                                allocator, len, data);
}
void   kkdcp_config__free_unpacked
                     (KkdcpConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kkdcp_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reloadable_config__init
                     (ReloadableConfig         *message)
{
  static const ReloadableConfig init_value = RELOADABLE_CONFIG__INIT;
  *message = init_value;
}
size_t reloadable_config__get_packed_size
                     (const ReloadableConfig *message)
{
  assert(message->base.descriptor == &reloadable_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reloadable_config__pack
                     (const ReloadableConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reloadable_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reloadable_config__pack_to_buffer
                     (const ReloadableConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reloadable_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReloadableConfig *
       reloadable_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReloadableConfig *)
     protobuf_c_message_unpack (&reloadable_config__descriptor,
                                allocator, len, data);
}
void   reloadable_config__free_unpacked
                     (ReloadableConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &reloadable_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor network_config__field_descriptors[15] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_netmask",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, ipv4_netmask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_network",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, ipv4_network),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, ipv4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_local",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, ipv4_local),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_network",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, ipv6_network),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_prefix",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetworkConfig, has_ipv6_prefix),
    offsetof(NetworkConfig, ipv6_prefix),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, ipv6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_local",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, ipv6_local),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtu",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetworkConfig, has_mtu),
    offsetof(NetworkConfig, mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_subnet_prefix",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetworkConfig, has_ipv6_subnet_prefix),
    offsetof(NetworkConfig, ipv6_subnet_prefix),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "routes",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(NetworkConfig, n_routes),
    offsetof(NetworkConfig, routes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_routes",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(NetworkConfig, n_no_routes),
    offsetof(NetworkConfig, no_routes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dns",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(NetworkConfig, n_dns),
    offsetof(NetworkConfig, dns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nbns",
    15,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(NetworkConfig, n_nbns),
    offsetof(NetworkConfig, nbns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned network_config__field_indices_by_name[] = {
  13,   /* field[13] = dns */
  3,   /* field[3] = ipv4 */
  4,   /* field[4] = ipv4_local */
  1,   /* field[1] = ipv4_netmask */
  2,   /* field[2] = ipv4_network */
  7,   /* field[7] = ipv6 */
  8,   /* field[8] = ipv6_local */
  5,   /* field[5] = ipv6_network */
  6,   /* field[6] = ipv6_prefix */
  10,   /* field[10] = ipv6_subnet_prefix */
  9,   /* field[9] = mtu */
  0,   /* field[0] = name */
  14,   /* field[14] = nbns */
  12,   /* field[12] = no_routes */
  11,   /* field[11] = routes */
};
static const ProtobufCIntRange network_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor network_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetworkConfig",
  "NetworkConfig",
  "NetworkConfig",
  "",
  sizeof(NetworkConfig),
  15,
  network_config__field_descriptors,
  network_config__field_indices_by_name,
  1,  network_config__number_ranges,
  (ProtobufCMessageInit) network_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kkdcp_realm_config__field_descriptors[5] =
{
  {
    "realm",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KkdcpRealmConfig, realm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(KkdcpRealmConfig, has_addr),
    offsetof(KkdcpRealmConfig, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ai_family",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(KkdcpRealmConfig, has_ai_family),
    offsetof(KkdcpRealmConfig, ai_family),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ai_socktype",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(KkdcpRealmConfig, has_ai_socktype),
    offsetof(KkdcpRealmConfig, ai_socktype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ai_protocol",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(KkdcpRealmConfig, has_ai_protocol),
    offsetof(KkdcpRealmConfig, ai_protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kkdcp_realm_config__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  2,   /* field[2] = ai_family */
  4,   /* field[4] = ai_protocol */
  3,   /* field[3] = ai_socktype */
  0,   /* field[0] = realm */
};
static const ProtobufCIntRange kkdcp_realm_config__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor kkdcp_realm_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KkdcpRealmConfig",
  "KkdcpRealmConfig",
  "KkdcpRealmConfig",
  "",
  sizeof(KkdcpRealmConfig),
  5,
  kkdcp_realm_config__field_descriptors,
  kkdcp_realm_config__field_indices_by_name,
  2,  kkdcp_realm_config__number_ranges,
  (ProtobufCMessageInit) kkdcp_realm_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kkdcp_config__field_descriptors[2] =
{
  {
    "url",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KkdcpConfig, url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "realms",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(KkdcpConfig, n_realms),
    offsetof(KkdcpConfig, realms),
    &kkdcp_realm_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kkdcp_config__field_indices_by_name[] = {
  1,   /* field[1] = realms */
  0,   /* field[0] = url */
};
static const ProtobufCIntRange kkdcp_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor kkdcp_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KkdcpConfig",
  "KkdcpConfig",
  "KkdcpConfig",
  "",
  sizeof(KkdcpConfig),
  2,
  kkdcp_config__field_descriptors,
  kkdcp_config__field_indices_by_name,
  1,  kkdcp_config__number_ranges,
  (ProtobufCMessageInit) kkdcp_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reloadable_config__field_descriptors[88] =
{
  {
    "is_dyndns",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_is_dyndns),
    offsetof(ReloadableConfig, is_dyndns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "listen_proxy_proto",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_listen_proxy_proto),
    offsetof(ReloadableConfig, listen_proxy_proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stats_report_time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_stats_report_time),
    offsetof(ReloadableConfig, stats_report_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cert_req",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_cert_req),
    offsetof(ReloadableConfig, cert_req),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable_compression",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_enable_compression),
    offsetof(ReloadableConfig, enable_compression),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_compress_limit",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_no_compress_limit),
    offsetof(ReloadableConfig, no_compress_limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "select_group_by_url",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_select_group_by_url),
    offsetof(ReloadableConfig, select_group_by_url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auto_select_group",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_auto_select_group),
    offsetof(ReloadableConfig, auto_select_group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "append_routes",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_append_routes),
    offsetof(ReloadableConfig, append_routes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "restrict_user_to_routes",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_restrict_user_to_routes),
    offsetof(ReloadableConfig, restrict_user_to_routes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deny_roaming",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_deny_roaming),
    offsetof(ReloadableConfig, deny_roaming),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cookie_timeout",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ReloadableConfig, has_cookie_timeout),
    offsetof(ReloadableConfig, cookie_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_timeout",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ReloadableConfig, has_session_timeout),
    offsetof(ReloadableConfig, session_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "persistent_cookies",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_persistent_cookies),
    offsetof(ReloadableConfig, persistent_cookies),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rekey_time",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ReloadableConfig, has_rekey_time),
    offsetof(ReloadableConfig, rekey_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rekey_method",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_rekey_method),
    offsetof(ReloadableConfig, rekey_method),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ban_time",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ReloadableConfig, has_ban_time),
    offsetof(ReloadableConfig, ban_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_ban_score",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_max_ban_score),
    offsetof(ReloadableConfig, max_ban_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ban_reset_time",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ReloadableConfig, has_ban_reset_time),
    offsetof(ReloadableConfig, ban_reset_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ban_points_wrong_password",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_ban_points_wrong_password),
    offsetof(ReloadableConfig, ban_points_wrong_password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ban_points_connect",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_ban_points_connect),
    offsetof(ReloadableConfig, ban_points_connect),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ban_points_kkdcp",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_ban_points_kkdcp),
    offsetof(ReloadableConfig, ban_points_kkdcp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_dtls_and_tls",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_match_dtls_and_tls),
    offsetof(ReloadableConfig, match_dtls_and_tls),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtls_psk",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_dtls_psk),
    offsetof(ReloadableConfig, dtls_psk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtls_legacy",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_dtls_legacy),
    offsetof(ReloadableConfig, dtls_legacy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isolate",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_isolate),
    offsetof(ReloadableConfig, isolate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth_timeout",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_auth_timeout),
    offsetof(ReloadableConfig, auth_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idle_timeout",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_idle_timeout),
    offsetof(ReloadableConfig, idle_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mobile_idle_timeout",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_mobile_idle_timeout),
    offsetof(ReloadableConfig, mobile_idle_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "switch_to_tcp_timeout",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_switch_to_tcp_timeout),
    offsetof(ReloadableConfig, switch_to_tcp_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keepalive",
    31,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_keepalive),
    offsetof(ReloadableConfig, keepalive),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dpd",
    32,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_dpd),
    offsetof(ReloadableConfig, dpd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mobile_dpd",
    33,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_mobile_dpd),
    offsetof(ReloadableConfig, mobile_dpd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_clients",
    34,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_max_clients),
    offsetof(ReloadableConfig, max_clients),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_same_clients",
    35,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_max_same_clients),
    offsetof(ReloadableConfig, max_same_clients),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_utmp",
    36,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_use_utmp),
    offsetof(ReloadableConfig, use_utmp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tunnel_all_dns",
    37,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_tunnel_all_dns),
    offsetof(ReloadableConfig, tunnel_all_dns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_occtl",
    38,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_use_occtl),
    offsetof(ReloadableConfig, use_occtl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "try_mtu",
    39,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_try_mtu),
    offsetof(ReloadableConfig, try_mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cisco_client_compat",
    40,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_cisco_client_compat),
    offsetof(ReloadableConfig, cisco_client_compat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cisco_svc_client_compat",
    41,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_cisco_svc_client_compat),
    offsetof(ReloadableConfig, cisco_svc_client_compat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate_limit_ms",
    42,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_rate_limit_ms),
    offsetof(ReloadableConfig, rate_limit_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ping_leases",
    43,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_ping_leases),
    offsetof(ReloadableConfig, ping_leases),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_drain_ms",
    44,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_server_drain_ms),
    offsetof(ReloadableConfig, server_drain_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_per_sec",
    45,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ReloadableConfig, has_rx_per_sec),
    offsetof(ReloadableConfig, rx_per_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_per_sec",
    46,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ReloadableConfig, has_tx_per_sec),
    offsetof(ReloadableConfig, tx_per_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "net_priority",
    47,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_net_priority),
    offsetof(ReloadableConfig, net_priority),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_buffer",
    48,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_output_buffer),
    offsetof(ReloadableConfig, output_buffer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_mtu",
    49,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_default_mtu),
    offsetof(ReloadableConfig, default_mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "predictable_ips",
    50,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_predictable_ips),
    offsetof(ReloadableConfig, predictable_ips),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_bypass_protocol",
    51,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ReloadableConfig, has_client_bypass_protocol),
    offsetof(ReloadableConfig, client_bypass_protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gssapi_no_local_user_map",
    52,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ReloadableConfig, has_gssapi_no_local_user_map),
    offsetof(ReloadableConfig, gssapi_no_local_user_map),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camouflage",
    53,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ReloadableConfig, has_camouflage),
    offsetof(ReloadableConfig, camouflage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_udp",
    54,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ReloadableConfig, has_no_udp),
    offsetof(ReloadableConfig, no_udp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expose_iroutes",
    55,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ReloadableConfig, has_expose_iroutes),
    offsetof(ReloadableConfig, expose_iroutes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cert_user_oid",
    100,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, cert_user_oid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cert_group_oid",
    101,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, cert_group_oid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "priorities",
    102,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, priorities),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "banner",
    103,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, banner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pre_login_banner",
    104,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, pre_login_banner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ocsp_response",
    105,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, ocsp_response),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_domain",
    106,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, default_domain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_select_group",
    107,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, default_select_group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crl",
    108,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, crl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route_add_cmd",
    109,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, route_add_cmd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route_del_cmd",
    110,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, route_del_cmd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connect_script",
    111,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, connect_script),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_update_script",
    112,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, host_update_script),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disconnect_script",
    113,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, disconnect_script),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cgroup",
    114,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, cgroup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proxy_url",
    115,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, proxy_url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xml_config_file",
    116,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, xml_config_file),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xml_config_hash",
    117,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, xml_config_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "per_group_dir",
    118,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, per_group_dir),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "per_user_dir",
    119,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, per_user_dir),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_group_conf",
    120,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, default_group_conf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_user_conf",
    121,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, default_user_conf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camouflage_secret",
    122,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, camouflage_secret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camouflage_realm",
    123,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, camouflage_realm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_list",
    200,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ReloadableConfig, n_group_list),
    offsetof(ReloadableConfig, group_list),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "friendly_group_list",
    201,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ReloadableConfig, n_friendly_group_list),
    offsetof(ReloadableConfig, friendly_group_list),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "custom_header",
    202,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ReloadableConfig, n_custom_header),
    offsetof(ReloadableConfig, custom_header),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "split_dns",
    203,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ReloadableConfig, n_split_dns),
    offsetof(ReloadableConfig, split_dns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "included_http_headers",
    204,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ReloadableConfig, n_included_http_headers),
    offsetof(ReloadableConfig, included_http_headers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "known_iroutes",
    205,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ReloadableConfig, n_known_iroutes),
    offsetof(ReloadableConfig, known_iroutes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network",
    300,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ReloadableConfig, network),
    &network_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_ports",
    301,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ReloadableConfig, n_fw_ports),
    offsetof(ReloadableConfig, fw_ports),
    &fw_port_st__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kkdcp",
    302,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ReloadableConfig, n_kkdcp),
    offsetof(ReloadableConfig, kkdcp),
    &kkdcp_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reloadable_config__field_indices_by_name[] = {
  8,   /* field[8] = append_routes */
  26,   /* field[26] = auth_timeout */
  7,   /* field[7] = auto_select_group */
  20,   /* field[20] = ban_points_connect */
  21,   /* field[21] = ban_points_kkdcp */
  19,   /* field[19] = ban_points_wrong_password */
  18,   /* field[18] = ban_reset_time */
  16,   /* field[16] = ban_time */
  58,   /* field[58] = banner */
  52,   /* field[52] = camouflage */
  78,   /* field[78] = camouflage_realm */
  77,   /* field[77] = camouflage_secret */
  56,   /* field[56] = cert_group_oid */
  3,   /* field[3] = cert_req */
  55,   /* field[55] = cert_user_oid */
  69,   /* field[69] = cgroup */
  39,   /* field[39] = cisco_client_compat */
  40,   /* field[40] = cisco_svc_client_compat */
  50,   /* field[50] = client_bypass_protocol */
  66,   /* field[66] = connect_script */
  11,   /* field[11] = cookie_timeout */
  63,   /* field[63] = crl */
  81,   /* field[81] = custom_header */
  61,   /* field[61] = default_domain */
  75,   /* field[75] = default_group_conf */
  48,   /* field[48] = default_mtu */
  62,   /* field[62] = default_select_group */
  76,   /* field[76] = default_user_conf */
  10,   /* field[10] = deny_roaming */
  68,   /* field[68] = disconnect_script */
  31,   /* field[31] = dpd */
  24,   /* field[24] = dtls_legacy */
  23,   /* field[23] = dtls_psk */
  4,   /* field[4] = enable_compression */
  54,   /* field[54] = expose_iroutes */
  80,   /* field[80] = friendly_group_list */
  86,   /* field[86] = fw_ports */
  79,   /* field[79] = group_list */
  51,   /* field[51] = gssapi_no_local_user_map */
  67,   /* field[67] = host_update_script */
  27,   /* field[27] = idle_timeout */
  83,   /* field[83] = included_http_headers */
  0,   /* field[0] = is_dyndns */
  25,   /* field[25] = isolate */
  30,   /* field[30] = keepalive */
  87,   /* field[87] = kkdcp */
  84,   /* field[84] = known_iroutes */
  1,   /* field[1] = listen_proxy_proto */
  22,   /* field[22] = match_dtls_and_tls */
  17,   /* field[17] = max_ban_score */
  33,   /* field[33] = max_clients */
  34,   /* field[34] = max_same_clients */
  32,   /* field[32] = mobile_dpd */
  28,   /* field[28] = mobile_idle_timeout */
  46,   /* field[46] = net_priority */
  85,   /* field[85] = network */
  5,   /* field[5] = no_compress_limit */
  53,   /* field[53] = no_udp */
  60,   /* field[60] = ocsp_response */
  47,   /* field[47] = output_buffer */
  73,   /* field[73] = per_group_dir */
  74,   /* field[74] = per_user_dir */
  13,   /* field[13] = persistent_cookies */
  42,   /* field[42] = ping_leases */
  59,   /* field[59] = pre_login_banner */
  49,   /* field[49] = predictable_ips */
  57,   /* field[57] = priorities */
  70,   /* field[70] = proxy_url */
  41,   /* field[41] = rate_limit_ms */
  15,   /* field[15] = rekey_method */
  14,   /* field[14] = rekey_time */
  9,   /* field[9] = restrict_user_to_routes */
  64,   /* field[64] = route_add_cmd */
  65,   /* field[65] = route_del_cmd */
  44,   /* field[44] = rx_per_sec */
  6,   /* field[6] = select_group_by_url */
  43,   /* field[43] = server_drain_ms */
  12,   /* field[12] = session_timeout */
  82,   /* field[82] = split_dns */
  2,   /* field[2] = stats_report_time */
  29,   /* field[29] = switch_to_tcp_timeout */
  38,   /* field[38] = try_mtu */
  36,   /* field[36] = tunnel_all_dns */
  45,   /* field[45] = tx_per_sec */
  37,   /* field[37] = use_occtl */
  35,   /* field[35] = use_utmp */
  71,   /* field[71] = xml_config_file */
  72,   /* field[72] = xml_config_hash */
};
static const ProtobufCIntRange reloadable_config__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 100, 55 },
  { 200, 79 },
  { 300, 85 },
  { 0, 88 }
};
const ProtobufCMessageDescriptor reloadable_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ReloadableConfig",
  "ReloadableConfig",
  "ReloadableConfig",
  "",
  sizeof(ReloadableConfig),
  88,
  reloadable_config__field_descriptors,
  reloadable_config__field_indices_by_name,
  4,  reloadable_config__number_ranges,
  (ProtobufCMessageInit) reloadable_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
